# Generated by Django 3.1.7 on 2021-03-25 21:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scores',
            old_name='by',
            new_name='origin',
        ),
        migrations.RenameField(
            model_name='scores',
            old_name='predict',
            new_name='score',
        ),
        migrations.AddField(
            model_name='scores',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
